In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.3


Creating Arrays

In [3]:
#from python lists
a=[1,2,3,4,5]
print(type(a))

<class 'list'>


In [4]:
b=np.array(a)
print(type(b))

<class 'numpy.ndarray'>


In [5]:
print(a)
print(b)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
c=np.array([2,3,4,5])
print(c)
print(type(c))

[2 3 4 5]
<class 'numpy.ndarray'>


Arrange


In [7]:
arr=np.arange(9)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [8]:
arr=np.arange(4.5)
print(arr)
print(type(arr))

[0. 1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [9]:
#an array of ones
print(np.ones(2))

[1. 1.]


In [10]:
print(np.ones(3,dtype=int))

[1 1 1]


In [11]:
#add multiple dimensions
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

linspace

In [15]:
#create x values between a,b
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [17]:
np.linspace(start=0,stop=5,num=3)

array([0. , 2.5, 5. ])

In [20]:
np.linspace(start=0,stop=5,endpoint=False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [19]:
np.linspace(start=0,stop=5,endpoint=True)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

Full

In [21]:
np.full(shape=(2,2),fill_value=5,dtype=int)

array([[5, 5],
       [5, 5]])

Random

In [23]:
#Random:generate a random float between 0 and 1,depending on how many elements you want
np.random.random(2)

array([0.47532796, 0.1988455 ])

In [26]:
np.random.randint(low=40,high=50,size=3,dtype=int)

array([48, 40, 46], dtype=int32)

In [27]:
np.random.randint(low=40,high=50,size=(3,4),dtype=int)

array([[41, 41, 42, 49],
       [40, 49, 47, 46],
       [41, 42, 42, 40]], dtype=int32)

In [28]:
np.random.normal(loc=3,scale=1.5,size=3)

array([3.19897641, 1.44536741, 1.22647135])

In [29]:
np.random.normal(loc=0.0,scale=1.0,size=(2,3))

array([[-0.72756429,  0.26642496,  0.49796446],
       [-0.0069374 ,  0.25451116,  0.9595525 ]])

In [30]:
#eye:diagonal matrix full of ones
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
#Aside from using the existing methods,we can also use 2 dimensinal arrays to create special matrices
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [35]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [36]:
#size of array,total number of elements
print(a.size)

8


In [37]:
print(a.ndim)

2


In [38]:
print(a.shape)

(2, 4)
