Fundamental Array operation

In [2]:
import numpy as np

In [3]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr)

2
[[1 2 3]
 [4 5 6]]


Reshaping Arrays

In [4]:
print(arr.size)
print(arr.shape)

6
(2, 3)


In [5]:
arr2=arr.reshape(3,2)
print(f"arr2:{arr2}")

arr2:[[1 2]
 [3 4]
 [5 6]]


In [6]:
arr3=arr.reshape(6,1)
print(f"arr3:{arr3}")

arr3:[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [7]:
arr4=arr.reshape(1,6)
print(f"arr4:{arr4}")

arr4:[[1 2 3 4 5 6]]


Concatenation

In [8]:
#Join two or more arrays along an existing axis.
a=np.array([1,2,3])
b=np.array([4,5,6])

In [9]:
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [12]:
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

In [13]:
c=np.array([[1,2,3]])
d=np.array([[4,5,6]])

In [14]:
np.concatenate((c,d),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.concatenate((c,d),axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [16]:
np.concatenate((c,d),axis=None)

array([1, 2, 3, 4, 5, 6])

In [17]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e.ndim)
print(e)

2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
e.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Vectorization

In [19]:
g=[1,2,3,4,5]
h=[1,1,1,1,1]
#write a program to add elements of the same index together
arr1=np.array(g)
arr2=np.array(h)
arr1+arr2

array([2, 3, 4, 5, 6])

In [20]:
print(arr1)

[1 2 3 4 5]


In [21]:
arr1+10

array([11, 12, 13, 14, 15])

Broadcasting

In [22]:
#The ability of numpy to perform operations on arrays of different shapes
a=np.array([1,2,3])
b=2
a*b

array([2, 4, 6])

In [23]:
g=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(g)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [24]:
g-[10,20,30]

array([[ 0,  0,  0],
       [30, 30, 30],
       [60, 60, 60]])

Transposing:Switching rows to columns and vise-versa

In [25]:
a=np.array([[1,2,3]])
print(a.ndim)
print(a)

2
[[1 2 3]]


In [26]:
np.transpose(a)

array([[1],
       [2],
       [3]])