In [1]:
import numpy as np

In [2]:
x=np.array([2,1,4,3,7,6])

In [3]:
#sorting arrays
np.sort(x)

array([1, 2, 3, 4, 6, 7])

In [4]:
a=np.array([[34,12,11],[2,9,5],[6,3,8]])
print(a)

[[34 12 11]
 [ 2  9  5]
 [ 6  3  8]]


In [5]:
np.sort(a)

array([[11, 12, 34],
       [ 2,  5,  9],
       [ 3,  6,  8]])

In [6]:
np.sort(a,axis=None)

array([ 2,  3,  5,  6,  8,  9, 11, 12, 34])

In [7]:
np.sort(a,axis=0)  #column wise sorting

array([[ 2,  3,  5],
       [ 6,  9,  8],
       [34, 12, 11]])

In [8]:
np.sort(a,axis=1)  #row wise sorting

array([[11, 12, 34],
       [ 2,  5,  9],
       [ 3,  6,  8]])

In [9]:
np.sort(a,axis=-1) 

array([[11, 12, 34],
       [ 2,  5,  9],
       [ 3,  6,  8]])

In [10]:
np.sort(a,axis=None)[::-1]  #sorting in descending order

array([34, 12, 11,  9,  8,  6,  5,  3,  2])

In [11]:
np.sort(a,axis=-1)[::-1]  #row wise sorting in descending order

array([[ 3,  6,  8],
       [ 2,  5,  9],
       [11, 12, 34]])

Argsort:sorts according to index

In [12]:
x=np.array([4,1,6,3])
np.sort(x)
np.argsort(x)  #gives indices of sorted array

array([1, 3, 0, 2])

Partition

In [13]:
#finding the k smallest value in an array
#3 smallest elements in an array
arr=np.array([3,7,9,5,2,1,8])
np.partition(arr,4)

array([1, 2, 3, 5, 7, 8, 9])

In [14]:
arr2=np.array([7,2,9,4,1,5,8,3,6])
np.sort(arr2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.partition(arr2,(3,5))

array([1, 2, 3, 4, 5, 6, 8, 9, 7])

In [16]:
arr3=np.array([72,54,33,89,56])
np.sort(arr3)
np.partition(arr3,2)

array([33, 54, 56, 72, 89])

index 3;89
index 4;56

In [19]:
np.partition(arr3,(2,4))

array([33, 54, 56, 72, 89])

Along a specific axis

In [28]:
#random state;(42)
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
np.random.randint(0,10,(4,6))

array([[9, 3, 7, 7, 8, 9],
       [3, 9, 9, 3, 7, 6],
       [4, 4, 5, 9, 0, 9],
       [7, 6, 2, 3, 1, 3]], dtype=int32)

In [29]:
np.partition(x,3,axis=1)  #row wise 3 smallest elements

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

In [30]:
np.partition(x,2,axis=0)  #column wise 2 smallest elements

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

Basic Math Operations

In [31]:
arr1=np.random.rand(10)
arr2=np.random.rand(10)

In [32]:
np.add(arr1,arr2)

array([1.7680807 , 0.61784646, 1.65968854, 0.45566106, 1.12336889,
       1.02369834, 0.73462995, 1.00470403, 1.04295508, 1.03907469])

In [33]:
np.subtract(arr1,arr2)

array([ 0.17738731,  0.54621813,  0.22026076,  0.20238169,  0.22863002,
       -0.68617492,  0.28282757, -0.33651068,  0.4864193 , -0.18458756])

In [34]:
np.multiply(arr1,arr2)

array([0.77366078, 0.020845  , 0.67651281, 0.04166716, 0.3024215 ,
       0.14428057, 0.11492243, 0.22404769, 0.21278789, 0.26140091])

In [35]:
np.divide(arr1,arr2)

array([ 1.22303143, 16.25145722,  1.30603934,  2.59809063,  1.51105417,
        0.19739675,  2.25199684,  0.49820014,  2.74802525,  0.69830309])

In [36]:
np.abs(-2)

np.int64(2)

In [37]:
np.power(3,2)

np.int64(9)

In [38]:
np.log(100)

np.float64(4.605170185988092)

In [39]:
np.log10(100)  #base 10 logarithm

np.float64(2.0)

In [40]:
a=np.array([-1.7,-1.5,0.2,2.4,2.6])
np.floor(a)  #rounding to lower integer

array([-2., -2.,  0.,  2.,  2.])

In [41]:
np.ceil(a)   #rounding to upper integer

array([-1., -1.,  1.,  3.,  3.])

Accessing elements witin an array

In [43]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [44]:
a[2,4]

np.int64(19)

In [45]:
a[:,2]  #3rd column

array([ 3, 10, 17])

In [46]:
a[2,:]  #3rd row

array([15, 16, 17, 18, 19, 20, 21])

In [47]:
a[:,:4]  #first 4 columns of all rows

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18]])

In [48]:
a[:,1:4]  #2nd to 4th column of all rows

array([[ 2,  3,  4],
       [ 9, 10, 11],
       [16, 17, 18]])

In [49]:
a[:2,:]  #first 2 rows of all columns

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [50]:
a[1:2,2:5]  #2nd row and 3rd to 5th column

array([[10, 11, 12]])

In [51]:
a[1,0:-1:3] #2nd row and all columns with step size of 3

array([ 8, 11])