# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [11]:
arr=np.zeros((3,3),dtype=int)
arr[1,1]=5
print(arr)


[[0 0 0]
 [0 5 0]
 [0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0*np.nan            = nan
np.nan==np.nan      = False
np.inf>np.nan       =False
np.nan - np.nan     = nan
np.nan in set([np.nan]) =True
0.3==3*0.1          = False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [15]:
arr=np.diag([1,2,3,4], k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
checkerboard=np.zeros((8,8),dtype=int)
checkerboard[1::2,::2]=1
checkerboard[::2,1::2]=1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [18]:
shape=(6,7,8)
index=np.unravel_index(99,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [19]:
checkerboard=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
np.random.random(size=(5,5))
np.random.normal(size=(5,5))

array([[ 0.37463919, -1.29199448, -1.70769833, -0.30663011, -0.13736413],
       [-0.18173484, -1.81048216,  0.39381143,  0.44785013, -1.69346705],
       [-0.18705793, -1.46866202,  1.03493155, -0.37054661, -0.64615011],
       [-1.62816554,  0.73666142,  1.49834289,  0.30319722,  0.80372724],
       [-1.19171993, -0.90027826,  0.82294222,  0.17415097, -0.1157402 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [2]:

color_dtype = np.dtype([("r", "u1"), ("g", "u1"), ("b", "u1"), ("a", "u1")])

# Example
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255)], dtype=color_dtype)

print(colors)
print(colors['r'], colors['g'], colors['b'], colors['a'])

[(255,   0, 0, 255) (  0, 255, 0, 255)]
[255   0] [  0 255] [0 0] [255 255]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [6]:
A = np.random.rand(5, 3)

# 3x2 matrix
B = np.random.rand(3, 2)

# Matrix multiplication (real product)
C = np.dot(A, B)        # or A @ B in Python 3.5+
# Result shape: (5,2)

print("A:\n", A)
print("B:\n", B)
print("C = A x B:\n", C)

A:
 [[0.53148746 0.57311535 0.24292257]
 [0.13816944 0.88864271 0.41424257]
 [0.29362325 0.6671522  0.42731665]
 [0.16461442 0.9692279  0.75712181]
 [0.19386384 0.87919101 0.21607355]]
B:
 [[0.15471674 0.36168263]
 [0.83878354 0.1726617 ]
 [0.35694013 0.25432167]]
C = A x B:
 [[0.64965854 0.35296533]
 [0.91461579 0.30875891]
 [0.75755118 0.33006595]
 [1.10868816 0.41943919]
 [0.84457025 0.27687198]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [3]:
arr = np.arange(10)
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [15]:
range(5) ==[0, 1, 2, 3, 4]
# 0+1+2+3+4 ==10
# 10 + (-1) == 9
np.sum(np.arange(5)) - 1

# Example with numpy imported as sum
print(np.sum(np.arange(5), axis=-1))


10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [18]:
Z = np.arange(5)
print((Z < Z) & (Z > Z))
print(np.power(Z, Z))
print((np.left_shift(2, Z)) >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)

[False False False False False]
[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [3]:
nan
0
array

NameError: name 'nan' is not defined

#### 29. How to round away from zero a float array ? (★☆☆)

In [2]:
arr=np.array([1.2,-1.2,1.5,-1.5,2.6,-2.6])
print(np.floor(arr))
print(np.ceil(arr))

[ 1. -2.  1. -2.  2. -3.]
[ 2. -1.  2. -1.  3. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [2]:
a=np.array([6,3,3])
b=np.array([4,5,6])
common=np.intersect1d(a,b)
print(common)




[6]
