# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

2.3.3


#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr=np.arange(10)
print(arr)
print(arr.size)

[0 1 2 3 4 5 6 7 8 9]
10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.add

<ufunc 'add'>

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
array = np.zeros(10,dtype=int)
array[4] = 1
print(array)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
np.arange(10,50)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.array([
    [0,1,2]
    ,[3,4,5]
    ,[6,7,8]
])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [4]:
arr=np.array([1,2,0,0,4,0])
arr_nonzero = np.nonzero(arr)
print(arr_nonzero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.76839488 0.26987689 0.80137439]
  [0.89307837 0.0136919  0.38005382]
  [0.87339525 0.74505869 0.52970172]]

 [[0.51850074 0.34072382 0.74624879]
  [0.92052883 0.57790991 0.88572126]
  [0.15864595 0.62889351 0.94883368]]

 [[0.3965155  0.72491181 0.09094904]
  [0.87975077 0.17387195 0.25001206]
  [0.77921944 0.37180193 0.71961137]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
arr=np.random.random((10,10))
min=arr.min()
max=arr.max()
print(arr)
print(min)
print(max)

[[0.04036397 0.88447503 0.47252324 0.67789059 0.01655865 0.93147766
  0.02247578 0.85790542 0.52859186 0.79695102]
 [0.13271499 0.84158646 0.51322227 0.20291999 0.30801425 0.25484338
  0.21572513 0.07960931 0.88238125 0.34334748]
 [0.89717912 0.00905919 0.75850201 0.06315935 0.43869231 0.37712357
  0.8146083  0.7408957  0.4165548  0.36991476]
 [0.14747837 0.25870705 0.47751562 0.04599554 0.65027445 0.34226603
  0.82073462 0.10154254 0.90600417 0.67766625]
 [0.7959994  0.86038164 0.46310973 0.69049533 0.4297112  0.97829723
  0.01303594 0.37309018 0.74712047 0.75667553]
 [0.9150115  0.00578959 0.98513521 0.1452727  0.32172792 0.89181936
  0.79835476 0.62479321 0.52717315 0.72661299]
 [0.54035078 0.23724354 0.68289489 0.26396227 0.95639112 0.03077428
  0.80457841 0.29432363 0.34300382 0.22808503]
 [0.04992118 0.42596145 0.22442184 0.37601305 0.08144191 0.02084779
  0.88591179 0.51093292 0.15684473 0.2165392 ]
 [0.51181086 0.726624   0.07607065 0.79640189 0.35275998 0.96925282
  0.25810638

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
arr=np.random.random(30)
mean=arr.mean()
print(arr)
print(mean)

[0.04767384 0.5359522  0.80699838 0.44642982 0.61600124 0.96093309
 0.0916888  0.53605264 0.25983732 0.64650559 0.43583437 0.47024492
 0.6894605  0.90505583 0.92123552 0.96038853 0.34527122 0.87303006
 0.60445136 0.22718697 0.87947352 0.8665233  0.66449294 0.97083516
 0.43175257 0.78262503 0.80476597 0.66458529 0.77653327 0.07448436]
0.6098767875364249


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
arr=np.ones((5,5),dtype=int)
arr[1:-1,1:-1]=0
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
