# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import warnings
warnings.filterwarnings('ignore')
# Numpy2.ipynb
# Numpy3.ipynb


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [4]:

yesterday = np.datetime64('today') - np.timedelta64(1, 'D')
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:    ", today)
print("Tomorrow: ", tomorrow)


Yesterday: 2025-09-14
Today:     2025-09-15
Tomorrow:  2025-09-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [5]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [6]:
import numpy as np

A = np.array([1., 2., 3., 4.])
B = np.array([5., 6., 7., 8.])

A += B      # (A+B) in place
A *= -0.5   # multiply by (-A/2) in place

print(A)


[-3. -4. -5. -6.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [7]:
Z = np.random.uniform(0, 10, 5)
print("Original:", Z)

# 1. np.floor
print(np.floor(Z))

# 2. np.trunc
print(np.trunc(Z))

# 3. astype(int)
print(Z.astype(int))

# 4. np.floor_divide
print(np.floor_divide(Z, 1))

Original: [5.37757926 9.17749734 5.14200584 2.189715   6.22855691]
[5. 9. 5. 2. 6.]
[5. 9. 5. 2. 6.]
[5 9 5 2 6]
[5. 9. 5. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [8]:
Z = np.tile(np.arange(5), (5, 1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [9]:
# Generator function
def gen():
    for i in range(10):
        yield i

# Build array from generator
Z = np.fromiter(gen(), dtype=int, count=10)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
Z = np.linspace(0, 1, 12)[1:-1]  # generate 12 points, drop first & last
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
a=([8,3,7,6,9,0,2,1,5,4])
np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [12]:
Z = np.arange(10)
print(sum(Z))


45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [13]:
A = np.random.rand(5)
B = np.random.rand(5)

print(np.array_equal(A, B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
Z = np.arange(10)
Z.flags.writeable = False  # make it immutable

print(Z)


[0 1 2 3 4 5 6 7 8 9]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [15]:
Z = np.random.rand(10, 2)   # 10x2 cartesian coords
R = np.linalg.norm(Z, axis=1)
T = np.arctan2(Z[:,1], Z[:,0])

print(np.column_stack((R, T)))

[[0.76528516 0.66695357]
 [0.97434499 1.02171014]
 [0.55460987 0.60126478]
 [0.77513171 0.60534103]
 [0.28487926 1.1708056 ]
 [0.50954599 0.61314576]
 [0.79168103 1.33944383]
 [0.62689295 0.36395757]
 [1.15452877 0.70145088]
 [0.93416533 0.04473875]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [16]:
Z = np.random.rand(10)
Z[Z.argmax()] = 0   # replace max with 0
print(Z)

[0.48997542 0.84133077 0.         0.69177115 0.86656521 0.66709577
 0.9273386  0.16954076 0.83215079 0.64086788]
